config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Routes pour les restaurants
  resources :restaurants, only: [:index, :new, :create, :show] do
    # Routes pour les avis associés à un restaurant
    resources :reviews, only: [:new, :create]
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant créé avec succès.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end


  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.new(review_params)
    if @review.save
      redirect_to @restaurant, notice: 'Review successfully added'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
  </head>

  <body>
  <!-- Barre de navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/restaurants">Yelp MVP</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to 'Liste des restaurants', restaurants_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Ajouter un restaurant', new_restaurant_path, class: 'nav-link' %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container mt-4">
      <!-- Contenu de la page spécifique -->
      <%= yield %> <!-- C'est ici que le contenu spécifique des pages sera affiché -->
    </div>



  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: ['chinese', 'italian', 'japanese', 'french', 'belgian'] %>
  <%= f.button :submit, 'Créer le restaurant', class: 'btn btn-success' %>
<% end %>

app/views/restaurants/index.html.erb
<h1>Liste des Restaurants</h1>


<table class="table mt-3">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Catégorie</th>
      <th>Actions</th>
    </tr>
  </thead>
 <tbody>
  <% @restaurants.each do |restaurant| %>
    <tr>
      <td><%= restaurant.name %></td>
      <td><%= restaurant.category %></td>
      <td>
        <%= link_to restaurant_path(restaurant), class: 'btn btn-outline-dark' do %>
          <i class="fa-sharp-duotone fa-solid fa-magnifying-glass"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
</tbody>


</table>

app/views/restaurants/new.html.erb
<h1>Ajouter un restaurant</h1>

<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: ['chinese', 'italian', 'japanese', 'french', 'belgian'] %>
  <%= f.button :submit, 'Créer le restaurant', class: 'btn btn-outline-dark' %>
<%= link_to restaurants_path, class: 'btn btn-outline-secondary' do %>
  <i class="fa fa-list"></i> Retour
<% end %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><strong>Adresse</strong> : <%= @restaurant.address %></p>
<p><strong>Numéro de téléphone</strong> : <%= @restaurant.phone_number %></p>
<p><strong>Catégorie</strong> : <%= @restaurant.category %></p>

<h2>Avis :</h2>

<%= render @restaurant.reviews %> <!-- Affiche tous les avis associés au restaurant -->
<%= link_to new_restaurant_review_path(@restaurant), class: 'btn btn-outline-dark' do %>
  <i class="fa fa-plus"></i> Ajouter un avis
<% end %>



<%= render 'reviews/form' %>

app/views/reviews/_form.html.erb
<!-- Formulaire pour laisser un avis -->

<%= simple_form_for [@restaurant, @restaurant.reviews.build] do |f| %>
  <%= f.input :rating, collection: [0, 1, 2, 3, 4, 5], prompt: "Choisir une note (0 à 5)", label: "Note" %>
  <%= f.input :content, as: :text, label: "Contenu" %>
  <%= button_tag type: 'submit', class: "btn btn-outline-dark" do %>
      <i class="fa fa-plus" >Ajouter un avis</i>
  <% end %>
  <%= link_to restaurants_path, class: 'btn btn-outline-secondary' do %>
  <i class="fa fa-list"></i> Retour
<% end %>
<% end %>


<div class="small-3 columns">

</div>

app/views/reviews/_review.html.erb
<div class="review">
  <p><strong>Note :</strong> <%= review.rating %>/5</p>
  <p><strong>Commentaire :</strong> <%= review.content %></p>
</div>

app/views/reviews/new.html.erb
<h1>Ajouter un avis pour <%= @restaurant.name %></h1>

<%= render 'reviews/form' %> <!-- Affiche le formulaire d'ajout d'avis -->